package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Chef;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ChefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CHEF
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CHEF
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    int insert(Chef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CHEF
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    Chef selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CHEF
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    List<Chef> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CHEF
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    int updateByPrimaryKey(Chef record);
}