package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Restaurant;
import org.mybatis.cdi.Mapper;

@Mapper
public interface RestaurantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESTAURANT
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESTAURANT
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    int insert(Restaurant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESTAURANT
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    Restaurant selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESTAURANT
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    List<Restaurant> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESTAURANT
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    int updateByPrimaryKey(Restaurant record);
}