package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Section;
import org.mybatis.cdi.Mapper;

@Mapper
public interface SectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SECTION
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SECTION
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    int insert(Section record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SECTION
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    Section selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SECTION
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    List<Section> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SECTION
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    int updateByPrimaryKey(Section record);
}