package lt.vu.mybatis.model;

public class Chef {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CHEF.ID
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CHEF.NAME
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CHEF.SECTION_ID
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    private Integer sectionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CHEF.ID
     *
     * @return the value of PUBLIC.CHEF.ID
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CHEF.ID
     *
     * @param id the value for PUBLIC.CHEF.ID
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CHEF.NAME
     *
     * @return the value of PUBLIC.CHEF.NAME
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CHEF.NAME
     *
     * @param name the value for PUBLIC.CHEF.NAME
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CHEF.SECTION_ID
     *
     * @return the value of PUBLIC.CHEF.SECTION_ID
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    public Integer getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CHEF.SECTION_ID
     *
     * @param sectionId the value for PUBLIC.CHEF.SECTION_ID
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    public void setSectionId(Integer sectionId) {
        this.sectionId = sectionId;
    }
}