package lt.vu.mybatis.model;

public class Restaurant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESTAURANT.ID
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESTAURANT.TITLE
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESTAURANT.ID
     *
     * @return the value of PUBLIC.RESTAURANT.ID
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESTAURANT.ID
     *
     * @param id the value for PUBLIC.RESTAURANT.ID
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESTAURANT.TITLE
     *
     * @return the value of PUBLIC.RESTAURANT.TITLE
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESTAURANT.TITLE
     *
     * @param title the value for PUBLIC.RESTAURANT.TITLE
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }
}