package lt.vu.mybatis.model;

public class Section {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SECTION.ID
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SECTION.NAME
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SECTION.RESTAURANT_ID
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    private Integer restaurantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SECTION.ID
     *
     * @return the value of PUBLIC.SECTION.ID
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SECTION.ID
     *
     * @param id the value for PUBLIC.SECTION.ID
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SECTION.NAME
     *
     * @return the value of PUBLIC.SECTION.NAME
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SECTION.NAME
     *
     * @param name the value for PUBLIC.SECTION.NAME
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SECTION.RESTAURANT_ID
     *
     * @return the value of PUBLIC.SECTION.RESTAURANT_ID
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    public Integer getRestaurantId() {
        return restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SECTION.RESTAURANT_ID
     *
     * @param restaurantId the value for PUBLIC.SECTION.RESTAURANT_ID
     *
     * @mbg.generated Thu Apr 30 14:16:09 EEST 2020
     */
    public void setRestaurantId(Integer restaurantId) {
        this.restaurantId = restaurantId;
    }
}